### ISSUE TITLE
Versions 3.0 and 3.1 not in Maven Repository

### ISSUE THREAD

**Issue by mmaihoefner** [eiswind/magnolia-thymeleaf-renderer#2]
Hello,

I wanted to try this Magnolia Add-on, but it seam like the lastest versions which support Thymeleaf3 are not in your Maven Repository. Can they be found in another Repository? Or could you please add them to your Repository? Thanks in advance!

**Comment by eiswind** [comment]
Unfortunately I cannot keep up with the latest versions of magnolia and thymeleaf, as I do not use this stuff anymore. Feel free to check out the project and build your own. The latest tested version is almost a year ago, so I guess you must update some dependencies to make it work with a up to date magnolia.

**Comment by mmaihoefner** [comment]
Thanks for your reply, its unfortunate that you can't update this module anymore, but i understand your reasoning. I might look into updating this project then, or use JSPs for my views.

**Comment by eiswind** [comment]
I just published 3.0.2 to bintray with support for thymeleaf 3.0.3.RELEASE
